apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log-pv-claim
  namespace: gitlab
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
